# Site settings
email: tommi.sahi@enli.fi
phone: 040 771 8567
baseurl: ''
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: UA-105010831-1

# SEO settings
title: ENLI Oy
description: > # this means to ignore newlines until "url:"
  ENLI OY on erikoistunut hoiva- ja palvelukiinteistöjen kehittämiseen ja rakennuttamiseen.
  Meillä on vuosien kokemus erilaisten hoiva- ja päiväkotien sekä seniori- ja
  palveluasuntokokonaisuuksien kehittämisestä, rahoittamisesta ja rakennuttamisesta.
url: www.enli.fi
default_img: /assets/images/hero_portrait.jpg

# Profile settings
name: Tommi Sahi
profile_img:
profile:
social:
  linkedin: https://fi.linkedin.com/in/tommisahi

# Build settings
exclude: [ "_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md" ]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
plugins: [ jekyll-feed, jekyll-paginate, jekyll-sitemap, octopress-autoprefixer, octopress-minify-html ]

prose:
  rooturl: 'docs'
  ignore: [ /\..*, '/site', '.gitignore', 'CNAME', 'LICENSE', 'package.json', 'README.md' ]
